### ISSUE TITLE
More Efficient Angular Rotation Ratios for faster polarimetry

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#1]
I created a demo in Katsu that steps through the Smith 2002 paper on polarimeter optimization to answer some questions I had about the paper. I found out that for a fixed rotation ratio between the PSG and PSA - there are two more efficient angular rotation ratios than what I used in the SCoOB paper (PSA rotation = 5x PSG rotation).

Shown in this figure is the condition number plotted against this rotation ratio. After around 4.91 it plateaus, but there lie minima at 2.5 and 3.5 that have the same condition number. This would half the time it takes to run DRRP, which is good if we are doing a lot of measurements. Each line represents a DRRP experiment conducted with a particular waveplate retardance.

![image](https://github.com/user-attachments/assets/631ab839-d5de-42d8-a336-ab6cc4235474)

**Comment by Jashcraf** [comment]
^The above is for N_measurements = 120. Here are a couple more for smaller numbers of measurements.

![image](https://github.com/user-attachments/assets/ca2fc1a4-c215-4bbb-a360-1132de2cfd01)
![image](https://github.com/user-attachments/assets/456bb7f8-42bc-43de-9404-705accf64b14)
![image](https://github.com/user-attachments/assets/026ee8c7-709d-459d-8be4-96aee15e14af)
![image](https://github.com/user-attachments/assets/f50b900a-3965-4338-98f9-6dc86a6fa9a1)

It looks like N = 40 is the minimum to get the minimum condition number, so @wcmelby was doing it right 👍. Another interesting thing is how smooth this gets as you add more measurements. It literally “pushes out” the noisy solution space.

**Comment by maxwellmb** [comment]
Great find!! I haven't looked at Smith before. How different is this to their approach? Is it worth spinning up an overleaf to dump this in, and maybe a place to also eventually put the error analysis we had discussed? 

Other thoughts:
- post the demo in this repo?
- have we hit a fundamental limit in the condition number? It certainly looks like there's a floor. Is there a way to prove it?

**Comment by Jashcraf** [comment]
So the demo is currently in `Katsu/docs`, I’ve linked it below:
https://github.com/Jashcraf/katsu/blob/main/docs/notebooks/PolarimeterOptimization.ipynb

Still playing around, but as expected (and as a lot of people know already) retardance + angular rotation ratio are the biggest factors in condition number. 

Here are the main references on the DRRP
- [Smith 2002](https://opg.optica.org/ao/abstract.cfm?uri=ao-41-13-2488)
- [Twietmyer and Chipman 2008](https://opg.optica.org/oe/fulltext.cfm?uri=oe-16-15-11589&id=169381)

**Re: Overleaf**
- I was actually thinking that this analysis is decent as a “letter” or “commentary” in a journal like JATIS or OE because it’s a direct response to work by Smith, and Twietmyer and Chipman. My thought (if you scroll down to near the bottom) is that it can be a published method of "optimizing a sub-optimal DRRP” to see if we can get substantial accuracy gains. The initial motivation is that 1/3-waveplates are hard to come by, and expensive, so we should do our darndest with QWPs to make the technique more accessible to the average investigator. I’m basically able to reproduce Smith’s brute-forcing of the solution space in like 30s, so running more iterations with model uncertainty is trivial. If we go this route, we could probably spin up a letter in like a couple weeks. If we want to add lab work, make that a couple of months maybe.
- I think a letter would then motivate the covariance optimization work w/ uncertainties with Jax. We can optimize an experiment for condition number _and/or_ minimum covariance in this follow-up paper (with Louis if possible). I’ve already started that [paper in an overleaf doc][https://www.overleaf.com/9828572311cyjwnfhngmdz#9b76fd]. Section 1.2 reviews the work of Smith, and Twietmyer and Chipman.

**Alternative Manuscript formats in SPIE Journals**
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/feecb481-3b90-43c5-a19e-4188be3759b8">
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/b6da0672-57ed-436e-9348-cb1fb1ecde77”>

A reason for OE (say, Commentary) is because there are probably Mueller polarimetry people on the reviewer list that will give it a nice, thorough look. A reason for JATIS Letters is to get the DRRP more visibility in Astronomy, where it really hasn’t been implemented.

What are your thoughts on this split-publication strategy?

**Comment by Jashcraf** [comment]
Looks like my finding that quarter-wave plates only work “better” for bad solutions was about right
![image](https://github.com/user-attachments/assets/9de13255-bc0f-4544-be91-56f2506f999d)

But you can recover _some_ performance by bumping up the number of measurements, which ins’t too bad
![image](https://github.com/user-attachments/assets/f3ba2559-88e5-4afe-a1a1-512351a92aeb)

**Comment by maxwellmb** [comment]
In your notebook you show that a HWP is much better, but you note it misses any circuclar polarization component. Is there another metric we can calculate that either includes that fact, or perhaps its an orthogonal metric to the condition number?

**Comment by Jashcraf** [comment]
I don't know of one from a purely statistical point of view.

I suspect that "Area on the poincare sphere" might lead to something like that. A "good" polarimeter will always exhibit this figure-8 trajectory for what polarization states are sent / analyzed.

![image](https://github.com/user-attachments/assets/54252d7c-cb61-473e-98e5-3c2f97e37920)

Theres a tool somewhere that I found on JOSS (I'll have to find it, something like Pypol) that makes Poincare visualization easy. But I found that this Figure 8 was "narrower" when you use a quarter-wave instead of a third-wave plate

**Comment by Jashcraf** [comment]
Yeah I mean it's just to poke at how good of a metric condition number is

There's another that might be worth considering from the previously linked Chipman paper is the sum of the diagonal elements of the covariance matrix. Its somewhat forward-model dependent, but you could imagine that if you construct your forward model such that you account for sensitivity to all polarization states, then it would capture that effect.

**Comment by Jashcraf** [comment]
![image](https://github.com/user-attachments/assets/da616efc-191a-453f-aa5b-07d61a35ad90)

**Comment by Jashcraf** [comment]
Independently - Louis Desdoigts also suggested this as the optimizable error metric for Fisher Information polarimetry

**Comment by maxwellmb** [comment]
He's suggested the sum of diagonal elements?

**Comment by Jashcraf** [comment]
Specifically, he suggested

```python
EM = np.sum(np.sqrt(np.diag(covariance_matrix))) 
```

I'm not sure how important the square root is but otherwise it's identical to what Chipman used in the optimization w/ error sources paper

**Comment by Jashcraf** [comment]
I guess it gets the error metric in the same units as the log likelihood?

**Comment by maxwellmb** [comment]
So this metric relates the input measurements to the output measurements,
so can help with picking optimal design parameters, right? You're right,
this might better capture everything rather than the condition number.

The other covariance matrix we want though is the instrument parameters (so
things that will affect W) vs. output measurements, for the sensitivity
analysis, so we can figure out things like how precise our calibration of
the fast axes need to be and how repeatable the rotation gratings need to
be.

Just making sure we're still talking about both cases.

**Comment by Jashcraf** [comment]
oh I was just talking about the covariance matrix of the instrument parameters

**Comment by maxwellmb** [comment]
Do you see my point though? There's kind of two tasks there, right? Maybe
they're the same...

**Comment by Jashcraf** [comment]
Going to close this since its no longer "active"

**Comment by maxwellmb** [comment]
Github needs a "close, but remind me about this later" button.
