### ISSUE TITLE
Install PYPSFStack on Rayleigh for Vector Phase Retrieval

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#10]

**Comment by Jashcraf** [comment]
Installed the code, did not set up a Pytorch environment

**Comment by maxwellmb** [comment]
Out of curiosity, what is this package?

**Comment by Jashcraf** [comment]
It used autodiff and Pytorch to fit to polarization- and focus-diverse datasets so that you can retrieve Jones pupils
