### ISSUE TITLE
Purchase Zaber Rotation Stages

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#11]
https://www.zaber.com/products/rotary-stages

Apparently these are better than Thorlabs and are about the same price

**Comment by Jashcraf** [comment]
Added to cart, still need to purchase

Also needed an M27x0.5 -> SM1 adapter so that we can mount our optics in them, here's a screenshot of the CAD drawing where I found the thread type

![image](https://github.com/user-attachments/assets/6746c69f-77a5-45af-87f7-c01c859182f2)

**Comment by maxwellmb** [comment]
Do Thorlabs or Zaber sell them, or do we need to go third party?

**Comment by Jashcraf** [comment]
thorlabs, already on the shopping list
