### ISSUE TITLE
Look into SuperK SDK for automation of laser control

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#3]
This would be particularly helpful for "white light" polarimetry that lets us measure the dispersion of optics to see if there is a polarization dependence.

The NKT SDK can be found here https://www.nktphotonics.com/support/ 

And if you download the SDK and run the installer, it comes with some sample files that we can use as a template for Derpy, for example, I think this turns Emission on:
```python
from NKTP_DLL import * 
result = registerWriteU8('COM27', 15, 0x30, 3, -1) 
print('Setting emission ON - Extreme:', RegisterResultTypes(result))
```

**Comment by Jashcraf** [comment]
Here's a script that finds the open ports that we can connect to - useful for finding the laser probably

```python
from NKTP_DLL import *

print('Find modules on all existing and accessible ports - Might take a few seconds to complete.....')
if (getLegacyBusScanning()):
    print('Scanning following ports in legacy mode:', getAllPorts())
else:
    print('Scanning following ports in normal mode:', getAllPorts())

# Use the openPorts function with Auto & Live settings. This will scan and detect modules
# on all ports returned by the getAllPorts function.
# Please note that a port being in use by another application, will show up in this list but will
# not show any devices due to this port being inaccessible.
print(openPorts(getAllPorts(), 1, 1))

# All ports returned by the getOpenPorts function has modules (ports with no modules will automatically be closed)
print('Following ports has modules:', getOpenPorts())

# Traverse the getOpenPorts list and retrieve found modules via the deviceGetAllTypesV2 function
portlist = getOpenPorts().split(',')
for portName in portlist:
    result, devList = deviceGetAllTypesV2(portName)
    for devId in range(0, len(devList)):
        if (devList[devId] != 0):
            print('Comport:',portName,'Device type:',"0x%0.4X" % devList[devId],'at address:',devId)

# Close all ports
closeResult = closePorts('')
print('Close result: ', PortResultTypes(closeResult))


```

**Comment by maxwellmb** [comment]
Should we have a separate repository for laser control?

**Comment by Jashcraf** [comment]
I think the SDK is self-contained enough personally, all the controls look functionally (i.e. as functions) implemented in this one DLL that we would just be making a front-end for. My personal bias (if it isn't clear from `derp_control`) is to have an object-oriented interface for hardware.

It might be interesting to have an `exopolab.py` package (I just picked a name) that contains routines for all "common" devices that are used by multiple instruments, if that's of use. For example, the SuperK, CRED2 cameras, the Thorlabs rotation stages if we keep getting more of those. Then the instrument-specific repos can install that parent package and add some custom functionality as-needed.

**Comment by maxwellmb** [comment]
I like that last suggestion!

**Comment by maxwellmb** [comment]
Well. Let's dicuss. It might be leaner for each set of devices to have its
own repo, or at least module, no?

**Comment by Jashcraf** [comment]
We could submodule a `exopolab` repo into device-specific modules. I know some folks who like organizing that way but have not done it myself.

**Comment by maxwellmb** [comment]
One thing to consider in the repo vs. modules discussion is keeping the
requirements slim. We don't necessarily want someone to need DM-related
libraries in order to operate the camera, or vice-versa.

**Comment by wcmelby** [comment]
It looks like we can also get an external power lock monitor for the SuperK SELECT which could be helpful for keeping power stability ("+/- 0.5 % over many hours"). I can't find how much it costs though

**Comment by wcmelby** [comment]
Finished! The new functions, demo, and original documentation can all be found in the repository NKT_laser_control

**Comment by maxwellmb** [comment]
Linking the repository: https://github.com/UCSB-Exoplanet-Polarimetry-Lab/NKT_laser_control

**Comment by Jashcraf** [comment]
![image](https://github.com/user-attachments/assets/9fddca53-5443-4c5c-806e-8de78e77c139)

**Comment by maxwellmb** [comment]
this looks like exactly what we want!

**Comment by maxwellmb** [comment]
shall we close the issue?
