### ISSUE TITLE
Write an auto-focusing algorithm for the translation stage to get near a pupil plane

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#6]

**Comment by Jashcraf** [comment]
Not sure how to do this immediately, but doing an edge-detection thing where you draw a line across the pupil and maximize the first derivative of the line at a point could work as a first pass

**Comment by Jashcraf** [comment]
Implementation idea - Median along the vertical dimension to denoise the data and compute the absolute value of the gradient of that, and then maximize it.

There are degenerate solutions but it could be fun to try

**Comment by Jashcraf** [comment]
Solution degeneracy arises from Gibbs phenomena, (i.e. onion-ring diffraction haha). But doing a down-sampling could alias a lot of this away.

**Comment by maxwellmb** [comment]
Is there (going to be?) a pupil lens, or does the stage take us to a pupil?

**Comment by Jashcraf** [comment]
I think the stage can get us there based on what we saw in the lab last week, but we can definitely check
