### ISSUE TITLE
Add a temperature tolerance to `derpy.camera.CRED2`

### ISSUE THREAD

**Issue by Jashcraf** [UCSB-Exoplanet-Polarimetry-Lab/derp_control#8]

**Comment by Jashcraf** [comment]
This is already implemented in `camera.py` somewhere I think

**Comment by Andyzhou336** [comment]
I created a fork and added this to its "temp" branch. Need to be tested.

**Comment by Andyzhou336** [comment]
Changed the tolerance value to match the one in the __init__ function.

**Comment by Jashcraf** [comment]
@Andyzhou336 would you mind making a pull request for this code?

**Comment by Jashcraf** [comment]
![image](https://github.com/user-attachments/assets/dbef8c74-1dd5-4850-8476-952046b6ebce)

Just click the "new pull request" button on the top right

![image](https://github.com/user-attachments/assets/56f91e73-cd20-4c82-8cf2-0d97b3da3ca1)

Then select your branch from this drop down
